---
deployment:
  tasks:
    # Set the destination deployment path on your cPanel account.
    - export DEPLOYPATH=/home/jgpuhdee/public_html/boafo
    
    # 2. Build your Vite project. (If you build locally and just commit the final files, you can skip this step.)
    - npm install
    - npm run build

    # 3. Copy your build output to your deployment path.
    - /bin/cp -R dist/* $DEPLOYPATH
